Support of HttpServletRequest, HttpServletResponse and HttpSession types in SpringAnnotationScanner
smallrye/smallrye-open-api pull request #1829
Opened 2024-05-07 14:12 UTC by morettileo

Proposal for support of HttpServletRequest, HttpServletResponse and HttpSession types in SpringAnnotationScanner as discussed in https://github.com/smallrye/smallrye-open-api/issues/1824

2024-05-10 14:59 UTC, MikeEdgar commented
@morettileo , it's failing due to formatting. The easiest way to fix that is running `mvn verify` locally and it will auto-format the files, which can then be committed.

2024-05-10 15:33 UTC, morettileo commented
Hi @MikeEdgar, I was working on it, sorry. You are absolutely right, the newer jakarta classes must be supported. Now it does, tests are aligned and formatting should be ok.

2024-05-11 01:31 UTC, phillip-kruger requested changes

2024-05-11 01:31 UTC, phillip-kruger commented on extension-spring/pom.xml
> +        </dependency>
I think this should be `test` scope

2024-05-11 12:49 UTC, MikeEdgar approved these changes

2024-05-11 20:45 UTC, phillip-kruger approved these changes
LGTM

2024-05-11 20:45 UTC, merged