Enable selection of annotation scanners (#1370) via maven plugin config.
smallrye/smallrye-open-api pull request #1894
Opened 2024-07-03 14:05 UTC by Olard

Hi,

this PR adds the capability to configure which annotation scanners should be executed (as noted in #1370).

2024-07-03 23:03 UTC, MikeEdgar approved these changes
This looks good to me. @phillip-kruger wdyt?

2024-07-04 11:24 UTC, MikeEdgar requested changes
@Olard , minor update to the docs suggested. Please take a look.

2024-07-04 11:24 UTC, MikeEdgar commented on tools/maven-plugin/README.adoc
> +- `scanners` (List<String>) - To set the names of the AnnotationScanner implementations that should be executed.
```suggestion
- `scanners` (List<String>) - Names of the AnnotationScanner implementations that should be executed. If omitted or an empty list, all scanners will be executed. The names of the scanners available by default are `JAX-RS`, `Spring`, and `Vert.x`.
```

2024-07-04 11:34 UTC, Olard commented
> @Olard , minor update to the docs suggested. Please take a look.

Yes, seems more informative that way : )

2024-07-04 11:58 UTC, MikeEdgar approved these changes
Thanks for the PR

2024-07-04 11:59 UTC, merged